<?php
$payment = Mage::getModel('quickpaypayment/payment');
?>
<?php $_code = $this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content">
            <?php echo nl2br($this->getInstructions()); ?>
            <?php if ((int)$payment->getConfigData('transactionfee') == 1) : ?>
            <?php if ($payment->getConfigData('transactionfee')) : ?>
            <br>
            <br>
            <b><?php echo Mage::helper('quickpaypayment')->__("Tranaktionsgebyr"); ?></b>
            <br>
            <?php echo Mage::helper('quickpaypayment')->__("Der vil blive opkrævet et transaktionsgebyr ved brug af denne betalingsmetode. Gebyr størrelsen afhænger af kortvalg og vil blive tilføjet ved betaling."); ?>

            <?php endif; ?>
            <?php endif; ?>
            <br/>
            <?php if ($payment->getConfigData('brandingidchecked')!='') : ?>
            <br/>
            <input type="checkbox" name="quickpay_state[]" value="checkbox1"> <?php echo $this->__($payment->getConfigData('brandingidcheckedtext'));?><br/>
            <?php endif; ?>
        </div>
    </li>
</ul>