<?php
/* Upgraded to version 10 of protocol */

/**
 *  Signs the parameters with the api key, the pendant to the old md5
 */
function qpSign($params, $api_key) {
      ksort($params);
      $base = "";
      foreach ($params as $key => $value) {
	   $base .= $value . " ";
      };
      $base = substr($base, 0, -1);
      return hash_hmac("sha256", $base, $api_key);
}


$payment = Mage::getModel('quickpaypayment/payment');

$order = Mage::getModel('sales/order');
$order->loadByIncrementId($payment->getCheckout()->getLastRealOrderId());


// CACHE BLOCK HTML OUTPUT DISABLE HACK --> START
$success = explode("?", Mage::getUrl('quickpaypayment/payment/success')); // Removes wierd cache url attachment ?SID_U
$redirect = explode("?", Mage::getUrl('quickpaypayment/payment/cancel')); // Removes wierd cache url attachment ?SID_U
$callback = explode("?", Mage::getUrl('quickpaypayment/payment/callback')); // Removes wierd cache url attachment ?SID_U
// CACHE BLOCK HTML OUTPUT DISABLE HACK --> END


//3D secure kort.
$secure3DCards = array(
  'creditcard',
  'jcb',
  'maestro',
  'maestro-dk',
  'mastercard',
  'mastercard-dk',
  'mastercard-debet-dk',
  'visa',
  'visa-dk',
  'visa-electron',
  'visa-electron-dk',
);
$use3dSecure = ($payment->getConfigData('use3dsecure') == 1) ? true : false;

$cardlocktype = "";

if ($payment->getConfigData('cardtype') == 'specific-cards') {
  $specificcards = explode(",", $payment->getConfigData('specifikcardtypes'));
  foreach ($specificcards as $card) {
    if ($use3dSecure && in_array($card, $secure3DCards)) {
      $cardlocktype .= "3d-" . $card;
    } else {
      $cardlocktype .= $card;
    }
    $cardlocktype .= ",";
  }
} elseif ($payment->getConfigData('cardtype') == 'creditcard') {
  if ($use3dSecure) {
    $cardlocktype .= "3d-creditcard";
  } else {
    $cardlocktype .= 'creditcard';
  }
}
$cardlocktype = rtrim($cardlocktype, ",");

$protocolVersion = 'v10';

$quickpay_state = Mage::getSingleton('core/session')->getQuickpayState(); // Get array of selections
if (isset($quickpay_state[0]) && $quickpay_state[0]=='checkbox1') {
  $brandingId = $payment->getConfigData('brandingidchecked');
} else {
  $brandingId = $payment->getConfigData('brandingid');
}

$qpayment = Mage::getSingleton('core/session')->getQPayment();

$parameters = array(
  "version" => $protocolVersion,
  "merchant_id" => $payment->getConfigData("merchantnumber"),
  "agreement_id" => $payment->getConfigData("agreementid"), 
  "ordernumber" => $payment->getCheckout()->getLastRealOrderId(),
  "amount" => $order->getTotalDue() * 100,
  "currency" => $order->getOrderCurrency()->ToString(),
  "continueurl" => Mage::getUrl('quickpaypayment/payment/success'),
  "cancelurl" => Mage::getUrl('quickpaypayment/payment/cancel'),
  "callbackurl" => Mage::getUrl('quickpaypayment/payment/callback'),
  "language" => $payment->calcLanguage(Mage::app()->getLocale()->getLocaleCode()),
  "autocapture" => $payment->getConfigData('instantcapture'),
  "autofee" => $payment->getConfigData('transactionfee'),
  //"payment_methods" => $cardlocktype,
  "payment_methods" => $qpayment,
  "branding_id" => $brandingId,
  "google_analytics_tracking_id" => $payment->getConfigData('googleanalyticstracking'),
  "google_analytics_client_id" => $payment->getConfigData('googleanalyticsclientid')
);

// Calculate the checksum to use in the form
$checksum = qpSign($parameters, $payment->getConfigData("md5secret"));
$posturl = "https://payment.quickpay.net/"; // Todo: Its in the configuration data but wrong, find it $payment->getConfigData('post_url')


?>

  <form id="quickpaypayment" action="<?php echo $posturl; ?>" method="post">
    <input type="hidden" name="version" value="<?php echo $parameters['version']; ?>">
    <input type="hidden" name="merchant_id" value="<?php echo $parameters['merchant_id']; ?>">
    <input type="hidden" name="agreement_id" value="<?php echo $parameters['agreement_id']; ?>">
    <input type="hidden" name="order_id" value="<?php echo $parameters['ordernumber']; ?>">
    <input type="hidden" name="amount" value="<?php echo $parameters['amount']; ?>">
    <input type="hidden" name="currency" value="<?php echo $parameters['currency']; ?>">
    <input type="hidden" name="continueurl" value="<?php echo $parameters['continueurl']; ?>">
    <input type="hidden" name="cancelurl" value="<?php echo $parameters['cancelurl']; ?>">
    <input type="hidden" name="callbackurl" value="<?php echo $parameters['callbackurl']; ?>">
    <input type="hidden" name="language" value="<?php echo $parameters['language'];  ?>">
    <input type="hidden" name="autocapture" value="<?php echo $parameters['autocapture']; ?>">
    <input type="hidden" name="autofee" value="<?php echo $parameters['autofee'];?>">
    <input type="hidden" name="payment_methods" value="<?php echo $qpayment; ?>" />
    <input type="hidden" name="branding_id" value="<?php echo $parameters['branding_id']; ?>">
    <input type="hidden" name="google_analytics_tracking_id" value="<?php echo $parameters['google_analytics_tracking_id'];?>">
    <input type="hidden" name="google_analytics_client_id" value="<?php echo $parameters['google_analytics_client_id'];?>">
    <input type="hidden" name="checksum" value="<?php echo $checksum; ?>">
  </form>

  <script type="text/JavaScript">
    document.getElementById('quickpaypayment').submit();
  </script>

<?php exit(); ?>